flox/floxpkgs

flake.lock
flake.nix
flox.nix
pkgs/flox/default.nix

Recreated a default.nix for the flox application after flox flake was unflaked

Fix flox definition

---

templates/packageset/flake.nix
templates/packageset/flox.nix

This is a template to demonstrate (and test) the capability of floxpkgs and capacitor to automatically add attributes about packages added to a `/pkgs` directory in a package set

proposed new packageset template

---

apps/find-version.nix

Addresses https://github.com/flox/flox/issues/51.

Basic error reporting for failed jq lookups

---

templates/rust/flake.nix
templates/rust/pkgs/default.nix

Depends #28 (in order to keep discussion about where to put default.nix there)

Add Rust template

---

templates/floxEnv/flake.nix
templates/floxEnv/flox.toml

Depends https://github.com/flox/floxpkgs/pull/31

Add FloxEnv template

---

lib/flox-env.nix
templates/floxEnv/flake.nix
templates/floxEnv/flox.toml

Allow users to optionally specify stability, channel, and version

Support restructured catalog in flox-env

---

templates/elixir/flake.nix
templates/elixir/pkgs/default.nix

following the existing conventions

feat: elixir template

---

flake.lock
flake.nix
flox.nix
templates/_init/flake.nix
templates/_init/flox.nix
templates/buildBazelPackage/files/pkgs/default.nix
templates/buildGoModule/files/pkgs/default.nix
templates/buildPerlPackage/files/pkgs/default.nix
templates/buildPythonPackage/files/pkgs/default.nix
templates/buildRustPackage/files/pkgs/default.nix
templates/mixRelease/files/pkgs/default.nix
templates/mkDerivation-java/files/pkgs/default.nix
templates/mkDerivation-ruby/files/pkgs/default.nix
templates/mkDerivation/files/pkgs/default.nix
templates/mkYarnPackage/files/pkgs/default.nix

https://github.com/flox/flox-internal/pull/215

release!: Compatibility to flox `0.0.4`

---

flake.nix
flox.nix
lib/checks/testScript.nix
lib/mkFakeDerivation.nix
lib/mkFloxEnv.nix
modules/flox-env.nix
pkgs/testRunners/podman/default.nix
pkgs/testRunners/podman/src/container-main.sh
pkgs/testRunners/podman/src/runner.sh
plugins/catalog.nix
plugins/checks.nix
plugins/floxEnvs.nix

Migrate everything from flox-extras into floxpkgs.

init: remove flox-extras

---

templates/mixRelease/files/pkgs/default.nix

The current `mixRelease` builder uses `mixFodDeps` function to fetch dependencies, however it seems to fail on fetching any complex dependency. Try with `timex`, `vega-lite`, `explorer`.
The more dependable path for packaging an Elixir application would be use `mix2nix`. We will pay for the reliability of the deps fetching with an extra step for the user: running `mix2nix > deps.nix`, which depends on there being a `mix.lock` file. 
The workflow with this PR would look like:
flox init
flox develop
mix2nix > deps.nix
flox build
This PR allows for that and adds a few ancillary things:
use mix2nix,
allow the user to specify elixir version and modify comments,
delete mixFodDeps, 
add mix2nix and elixir to buildInputs so the user can develop with them, 
rework postBuild comments

modify mixRelease builder

---

lib/mkEnv.nix
modules/common.nix
modules/shells/posix.nix
plugins/floxEnvs.nix

Support develop with floxEnvs. Eg: `flox develop github:flox-examples/floxEnv/module-mkEnv#floxEnv`

feat: use mkEnv in floxEnvs

---

modules/common.nix

Although paths in the evalCatalog have underscores, JSON should have periods

fix: floxEnv: preserve . in JSON catalog paths

---

modules/options.nix
modules/shells/posix.nix

Variables is not specific enough

feat: rename variables -> environmentVariables

---

apps/default.nix
pkgs/flox-install/default.nix
pkgs/flox/default.nix

simplify flox installation. This supports
```
nix run github:flox/floxpkgs
```
and
```
nix profile install --impure github:flox/floxpkgs#flox.fromCatalog
```
and
```
nix shell --impure github:flox/floxpkgs/flox-install#flox.fromCatalog
```

Flox install

---

modules/container.nix

- set entrypoint and cmd such that
- podman run -it runs activation and drops into bash
- podman run cmd runs activation and then the command
- container.config.env should always be overriden with environmentVariables
- when flox activation is occurring, don't set env vars in container.config.env, since environmentVariables may need to be evaluated by a shell

fix(modules): entrypoint and env

---

flox.nix
plugins/floxEnvs.nix
plugins/rootFloxEnvs.nix

CLI commands do not understand these yet

feat: search for flox.nix at root

---

templates/project/files/flox.nix
templates/project/template.nix

This probably breaks our code for `flox init` since our logic there is pretty basic and wont handle `flox.nix` file at the root.

project template

---

lib/mkFakeDerivation.nix

Currently head of outputs may or may not actually be installed

fix: pick defaultOut from outputsToInstall

---

pkgs/flox-prerelease/default.nix

Provide catalog-style access to flox-prerelease.

feat: add flox-prerelease (catalog only) to floxpkgs

---

templates/profile/files/flox.nix

Add pkg-config to etc-profiles

---

modules/common.nix

Will search for evalCatalog,packages,legacyPackgaes.
Should this be conditional on some sort of `{catalog = false;}`, but then the UX is assymetrical.

feat: search for attributes in flake locations

---

flake.lock
flake.nix

Trying to fix the eval failure regarding revCount.

revert: use git+https for flox-*

---

flake.lock

release: flox@0.3.6
