flox/floxpkgs

- test/capacitor-default.exp
The test overrides the capacitor version to a commit given by the test runner.
As development branches (read "commits") are only available on *de*capacitor the injected capacitor commit needs to come from the decapacitor repository
> Fix capacitor-default.exp

- flake.lock
- flake.nix
This eliminates two copies of nixpkgs
> nix-editor and devshell follow nixpkgs

- lib/flox-env.nix
Capacitor removes the system attribute from inputs.nixpkgs.catalog, but
it does not currently choose the correct system on Darwin. getFlake was
used as a hack to get around the issue, but using args is a better
workaround
> flox-env: remove getFlake hack

- flake.lock
- flake.nix
- flox.nix
Integrates the partial catalog built by @samrose.
Eventually the catalog should be generated by a catalog flake or hosted in a more canonical place.
**This flake now makes use of `flox/flox-extras`.**
For customers this needs to be necessarily accessible
related: https://github.com/flox/flox/pull/151
> Add partial generated catalog

- templates/go/flake.nix
- templates/go/pkgs/default.nix
Depends https://github.com/flox/floxpkgs/pull/28  (in order to keep discussion about where to put default.nix there)
Fixes: https://github.com/flox/floxpkgs/issues/24
> Add up-to-date Go template

- flake.lock
- flake.nix
Previously installing flox depended on a working git and ssh installation which added another command in order to install flox.
Using the http based interface will avoid that!
This PR also adds the default flox substituter so cached build can be downloaded without extra build time.
@tomberek were going back and forth with the input url styles, do the git+ssh add that much in performance to warrant the additional work to install flox?
> Allow pull without git + add substituter

- templates/floxEnv/flake.nix
- templates/go/flake.nix
- templates/python/flake.nix
- templates/rust/flake.nix
Without this change, floxpkgs.evalCatalog.stable.nixpkgs does not exist
I don't fully understand this, and I thought we decided this wasn't necessary. But when I try to `flox develop` with the current floxEnv template, I'm getting:
```
error: attribute 'nixpkgs' missing
at /nix/store/143fvsgvx0lkiiav0kcv54yrnxfk5mdw-source/lib//flox-env.nix:62:41:
61|                   then withVersion (tail path) stability.${head path}
62|                   else withVersion path stability.nixpkgs;
|                                         ^
63|                 # translate version into an attrPath if it's provided. Otherwise, fallback to the
```
> Configure stabilities for templates

- templates/rust/pkgs/default.nix
Add comments about imports, outputHashes, and buildInputs
> feat: better document Rust template

- flake.lock
- flox.nix
- templates/_init/flake.nix
- templates/_init/flox.nix
- fix: point template to the right branch of floxpkgs
- fix: remove namespace from catalog
- fix: point catalog plugin to the right directory
> chore: 0.0.4 release cleanups

- .github/workflows/trigger-update.yml
With automated publishes, the update lockfile action is triggered four times (once for each system) in response to every update of the catalog.
Since nothing locked changes due to a push of a catalog entry, we should ignore these events
> ci:  do not update lockfile on push to `catalog` folder

- templates/mixRelease/files/pkgs/default.nix
the default.nix file is nested two folders down, not one.
> fix relative path for deps.nix

- templates/mixRelease/files/pkgs/default.nix
If we comment out `mixNixDeps` to start out with, the user can run `flox develop` which will bring `mix2nix` into scope, and will allow the user to run it, and then they can uncomment the mixNixDeps line and build the package
> refactor: comment mixNixDeps by default

- plugins/floxEnvs.nix
This will be needed for named environments, which will be subdirectories of FLOXMETA
> feat: support floxEnvs in repo subdirectories

- templates/_init/flake.nix
Disambiguate the various floxpkgs inputs by naming them according to their full "organization/project" paths, replacing "/" with "-".
> templates/_init/flake.nix: rename flox/floxpkgs input

- modules/common.nix
flox list expects the manifest to contain the flake referring to the channel from which a package was installed
> fix: floxEnv: set originalUrl to channel

- lib/mkEnv.nix
- modules/shells/posix.nix
The main purpose is to make lib.mkEnv available. The distinction between how this is done with mkFloxEnv is where the packages come from. This is a constant problem with lib functions that are system or pkgs-dependent. Not sure which style is best.
> fix!: require passing pkgs to lib.mkEnv

- flox.nix
Flakes built with floxpkgs.project should use the nixpkgs from floxpkgs, which is modified by flox' stability flags
> feat: inject default nixpkgs

- flake.lock
- flake.nix
- lib/withRevision.nix
- templates/buildBazelPackage/files/pkgs/default.nix
- templates/buildGoModule/files/pkgs/default.nix
- templates/buildPerlPackage/files/pkgs/default.nix
- templates/buildPythonPackage/files/pkgs/default.nix
- templates/buildRustPackage/files/pkgs/default.nix
- templates/mixRelease/files/pkgs/default.nix
- templates/mkDerivation-java/files/pkgs/default.nix
- templates/mkDerivation-ruby/files/pkgs/default.nix
- templates/mkDerivation/files/pkgs/default.nix
- templates/mkYarnPackage/files/pkgs/default.nix
The `withRev` function will append a "-rXXX" string to the version string to provide automatic tracking of version increments in package versions. Adding this to all templates by default.
> treewide: use withRev to set revisioned version in templates

- modules/options.nix
- modules/shells/posix.nix
This allows env vars to depend on state at activation time
> feat: support evaluated env vars

- lib/mkFakeDerivation.nix
- modules/common.nix
- Unfree packages do not have a cache entry and must be built from source
- Currently self package are wrapped in a fakeDerivation that can't be built from source, so instead just passthrough the actual derivation
- Use fetchClosure now that we have a value for fromStore
> unfree packages, fix self, use fetchClosure

- modules/common.nix
The floxEnv must be identical for the locking and locked build, so we have to call mkFakeDerivation even if we already have a fake derivation, because the version of mkFakeDerivation used by the catalog plugin may be different than the version called by the floxEnv modules
> fix(modules): always use the same version of mkFakeDerivation

- lib/mkFakeDerivation.nix
- modules/common.nix
- plugins/catalog.nix
The catalog plugin should not be dropping any data from publishData. In particular, this fixes the assumption in mkFakeDerivation that cache is passed. Also rename element -> publishData (this is a historical name from nix profile manifest elements)
> fix: pass all publishData to mkFakeDerivation

- lib/mkEnv.nix
- lib/mkFakeDerivation.nix
- valid is a boolean not a string
- mkEnv was missed in the recent rename of element
> fix: mkFakeDerivation related bugs

- flake.lock
- modules/common.nix
- plugins/floxEnvs.nix
Usage:
```
{
packages.nixpkgs-flox.hello = {version = "2.10";};
packages.nixpkgs-flox.ran = {};
packages.nixpkgs-flox.cheat = {};
packages.nixpkgs-flox.ripgrep = {};
packages.nixpkgs-flox.jq = {};
derivations = {
packages.env = {python3}:
python3.withPackages (ps: with ps; []);
};
}
```
> init: inline packages via capacitor

- lib/mkContainer.nix
- lib/mkFloxEnv.nix
- modules/container.nix
- modules/options.nix
- modules/shells/posix.nix
- plugins/floxEnvs.nix
If no entrypoint is specified, a floxEnv container starts by performing
(bash) activation. Otherwise, shell module options are ignored, and the
entrypoint is run in a container with the appropriate paths and env vars
> feat: add floxEnv container and module options

- modules/container.nix
Otherwise layers are never reused
I'm planning to tweak the script to allow both "now" and reuse, but for now allow reuse
> fix: default container.created to 1970

- lib/readPackage.nix
- modules/common.nix
Currently determining the contents of manifest.json and catalog.json requires realizing the storePath for a fakeDerivation. This is undesirable since we should be able to eval a catalog without performing any intensive operations in order to determine the available upgrades for an environment. Instead of realizing the fakeDerivation storePath, just pass through the storePaths that it wraps
Helps https://github.com/flox/product/issues/155
This means manifest.json and catalog.json may contain a storePaths with multiple storePaths rather than just a single one, and the output of flox list changes from:
```
Packages
0  stable.nixpkgs-flox.curl  /nix/store/07zipzdqcldqz5f6wdarc2dlxmwbydi9-curl-7.86.0
```
To:
```
Packages
0  stable.nixpkgs-flox.curl …
```
> fix: don't realize fakeDerivation for catalog.json

- modules/common.nix
Allows for an alias of "integrations" instead of the awkward "inline".
> feat: rename inline to integrations

- modules/common.nix
runix invokes nix eval with --json, which turns the output of toJSON into a single string rather than actual JSON
> fix: don't call toJSON

- modules/common.nix
`flox list` needs to be able to list the storePaths in a floxEnv. That information is currently present in manifest.json, but manifest.json is being deprecated.
Store paths could be added to catalog.json, but that would be abusing the purpose of the catalog. The purpose of the catalog is to express invariants about derivations. Adding a store path to a catalog would only express "this store path was present on some machine at some time" which is a useless guarantee. Additionally, a catalog entry for a store path would contain exactly the same information as the flox.nix file, which would mean useless duplication.
> feat: add installedStorePaths passthru

- modules/common.nix
- modules/container.nix
- modules/shells/posix.nix
- plugins/floxEnvs.nix
- plugins/rootFloxEnvs.nix
This is the follow up on the merged capacitor changes, allowing you to pass a system specialized context to the modules.
This is generally more consistent with how we use to call functions elsewhere when we have access to `system`
> feat: pass specialized context to flox envs

- flake.lock
- flake.nix
Allow development on flox/flox without impacting the released package.
> build: use `latest` flox release

- lib/mkFakeDerivation.nix
Currently substitution will be attempted even when valid == false. This
results in the error "path ... does not exist and cannot be created"
being displayed to the user rather than the correct behavior of
attempting to build from source.
> fix: only substitute if valid == true

- .github/workflows/etc-profiles.yml
- flake.lock
- flake.nix
- lib/buildenv/README.flox
- lib/buildenv/builder.pl
- lib/buildenv/default.nix
- lib/mkEnv.nix
- pkgs/etc-profiles/default.nix
- templates/profile/files/flox.nix
This patch updates the floxEnv builder to add all packages installed to a flox environment to the nix-support/propagated-user-env-packages file and adds a customized version of the nixpkgs buildEnv builder which recursively treats propagated-{build-inputs,user-env-packages} the same.
The effect of this change is to render symbolic links for all files both in directly installed packages _and_ their (recursive) propagated build input packages, so that files from these inputs can be found in their customary FHS location under $FLOX_ENV, and correspondingly means that $FLOX_ENV can be used in other variables like $PYTHONPATH.
Notably, this does _not_ increase the number of packages in the closure, it only increases the number of symbolic links found in the floxEnv package itself.
> feat: link propagated build inputs in floxEnvs

- lib/mkEnv.nix
The jq package is unusual in that it has a completely empty "out"
output which is not rendered by default, and passing a nonexistent
path to buildenv.pl causes it to fail.
This patch updates the logic to instead iterate over the outputs
specified by meta.outputsToInstall rather than blindly passing the
"out" output to the buildEnv function.
N.B. I'm intentionally leaving the builtins.trace call commented
out in place to make it easier to debug in future.
> fix: don't always pass "out" output to buildEnv

- .github/workflows/etc-profiles.yml
- templates/profile/files/flox.nix
Obviously the way we refer to `etc-profiles` is not a long term solution, but this works "today".
> fix: `etc-profiles` template works and adds various "common packages" by default

- .github/workflows/etc-profiles.yml
Extends an existing `etc-profiles` test with a requirement for `npm install krb5` to "just work".
> test: npm install krb5 module

- lib/checks/lockFlake.nix
- lib/lockFlake.nix
Handle special boolean query parameters in URI parser: `allRefs`, `submodules`, `shallow`.
> fix: handle bool params in URI parser

- flake.nix
- pkgs/flox-prerelease/default.nix
- pkgs/flox/default.nix
Reverting parts of #155 bringing back the "lazy derivations" for flox and flox-prerelease.
Re-export flox as a "lazy" derivation with an additional attribute `fromCatalog`
Adding an attribute to a canonical re-export such as
{ capacitated }:
capacitated.flox-main.packages.flox // {fromCatalog = self.evalCatalog.stable.flox; }
requires the evaluation of `capacitated.flox-main.packages.flox` to an attrset.
We want to allow installin packages from the catalog explicitly without any evaluation of the
upstream package (which involves fetching any number of additional flakes).
> build: use lazy derivations for flox packages

- .github/workflows/trigger-update.yml
We are triggering lockfile updates on `master` even on changes to PR branches.
This PR adds a filter to only run the update action in for changes to master.
> ci: only trigger lockfile updates on changes to `master`
